# DEFAULT]
# user=ocid1.user.oc1..aaaaaaaahtb5ka5gvoyvborzhjs4tf5l6pkrjlx6y3d27prj53yqs2ec3n7a
# fingerprint=9d:0a:90:9d:3c:c8:7c:a8:bd:58:59:a0:06:b5:3c:86
# tenancy=ocid1.tenancy.oc1..aaaaaaaaa63icmpjcpmkmjx7jhgcjes7nokpgf23fu4mupd7cwmerhiwgdba
# region=sa-saopaulo-1
# key_file=<path to your private keyfile> # TODO